version: '3.8' # Compose file format version 

services: # Containers that make up an appilcation
  backend:
    build: 
      context: ./backend
      dockerfile: Dockerfile.dockerfile
    container_name: parables-backend
    ports:
      - "8000:8000"
    env_file: # Uses local .env when run locally 
      - .env 
    depends_on: # Ensures database container starts before the backend
      - db

  frontend:
    build: 
      context: ./frontend
      dockerfile: Dockerfile.dockerfile
    container_name: parables-frontend
    ports:
      - "3000:80"
    depends_on:
      - backend

  db:
    image: postgres:14 # Use official image from Docker Hub 
    container_name: parables-db
    environment:
      POSTGRES_DB: ${DB_NAME:-parables}
      POSTGRES_USER: ${DB_USER:-postgres}
      POSTGRES_PASSWORD: ${DB_PASS:-postgres}
    volumes: # Persist database data when container stops or rebuilds 
      - pgdata:/var/lib/postgresql/data
    ports:
      - "5432:5432"

volumes:
  pgdata:
